version: "3"
services:

  # v -- NextJS | Frontend, react based compiled webapp.
  app:
    ports: [$APP_PORT:3000]

    image: node:lts-alpine
    restart: unless-stopped
    working_dir: /usr/app
    env_file: .env
    volumes: [.:/usr/app]
    command: ["yarn", "ci"]
    profiles: ["prod"]
