
name: Code Checks

on:
  pull_request:
    branches: main

jobs:
  Lint:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Code Linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
