
name: Code Checks

on:
  pull_request:
    branches: main

jobs:
  Lint:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Code Linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
